
    
version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "4444:3306"
    environment:
      MYSQL_ROOT_PASSWORD: client
    volumes:
      - ~/Desktop/13aug_microtst/backend/mysql_data:/var/lib/mysql
      
  springservice:
    container_name: spring-app
    image: dockerspringimg
    build: .
    ports:
      - "7777:7070"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: client
      MYSQL_USER: root


    